on: workflow_dispatch

jobs:
  test:
    name: Make tables
    runs-on: ubuntu-latest
    steps:
      - name: Install csvkit
        run: |
          sudo apt-get update
          sudo apt-get install csvkit
      - uses: actions/checkout@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Run script make_tables.sh
        run:  bash ${GITHUB_WORKSPACE}/scripts/make_tables.sh
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'tables'
          author_name: Knowledge Pixels Bot
          author_email: bot@knowledgepixels.com
          message: 'Add tables'
