on: workflow_dispatch

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Run script
        run:  bash ${GITHUB_WORKSPACE}/scripts/test.sh
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: 'table'
          author_name: Knowledge Pixels Bot
          author_email: bot@knowledgepixels.com
          message: 'Add tables'
